[package]
name = "ai00_server"
version = "0.2.2"
edition = "2021"
authors = ["Gu ZhenNiu <448885@qq.com>", "Zhang Zhenyuan <cryscan@umich.edu>"]
license = "MIT OR Apache-2.0"
description = "An implementation of the RWKV language model in pure WebGPU."
homepage = "https://github.com/cgisky1980/ai00_rwkv_server"
repository = "https://github.com/cgisky1980/ai00_rwkv_server"
keywords = ["deep-learning", "LLM", "model", "rwkv"]
categories = ["science"]
exclude = ["assets"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { git = "https://github.com/cryscan/axum", branch = "sse-leading-space" }
tower = { version = "0.4", features = ["util"] }
tower-http = { version = "0.4", features = ["full"] }
tokio = { version = "1", features = ["full"] }
pollster = "0.3"
# web-rwkv = "0.3.6"
web-rwkv = { git = "https://github.com/cryscan/web-rwkv", branch = "main" }
memmap = "0.7"
bytemuck = "1"
regex = "1.8"
clap = { version = "4.3", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
qp-trie = "0.8"
fastrand = "2"
itertools = "0.11"
flume = "0.10"
futures-util = "0.3"
rayon = "1.8"
anyhow = "1"
log = "0.4"
simple_logger = { version = "4.2", features = ["stderr"] }
zip-extract = "0.1"
tempfile = "3.6"
toml = "0.7"
sha2 = "0.9.8"

[profile.release]
lto = true
