[package]
name = "ai00_server"
version = "0.1.0"
edition = "2021"
authors = ["Gu ZhenNiu <448885@qq.com>"]
license = "MIT OR Apache-2.0"
description = "An implementation of the RWKV language model in pure WebGPU."
homepage = "https://github.com/cryscan/web-rwkv"
repository = "https://github.com/cryscan/web-rwkv"
keywords = ["deep-learning", "language", "model", "rwkv"]
categories = ["deep-learning", "rendering"]
exclude = ["assets"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
warp = "0.3"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
pollster = "0.3.0"
memmap2 = "0.7"
itertools = "0.11"
fastrand = "2.0"


[profile.release]
lto = true
codegen-units = 1
 