[package]
name = "ai00_server"
version = "0.1.2"
edition = "2021"
authors = ["Gu ZhenNiu <448885@qq.com>"]
license = "MIT OR Apache-2.0"
description = "An implementation of the RWKV language model in pure WebGPU."
homepage = "https://github.com/cryscan/web-rwkv"
repository = "https://github.com/cryscan/web-rwkv"
keywords = ["deep-learning", "language", "model", "rwkv"]
categories = ["science"]
exclude = ["assets"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { git = "https://github.com/cryscan/axum", branch = "sse-leading-space" }
tower = { version = "0.4", features = ["util"] }
tower-http = { version = "0.4", features = ["full"] }
tokio = { version = "1", features = ["full"] }
web-rwkv = "0.1.12"
memmap = "0.7"
clap = { version = "4.3", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
qp-trie = "0.8"
fastrand = "2"
itertools = "0.11"
flume = "0.10"
futures-util = "0.3"
anyhow = "1"

[profile.release]
lto = true
